-- Generated by scripts/reconcile-db-objects.mjs for the P0.13 quality gate
-- One authorization assertion for every application-referenced database object.

begin;
create extension if not exists pgtap with schema extensions;
set local search_path = public, extensions;
select plan(35);

-- P0.9-AUTH: P0.9-AUTH-001
select ok(
  exists (select 1 from storage.buckets where id = 'supplier-evidence')
  and exists (
      select 1
      from pg_policies
      where schemaname = 'storage'
        and tablename = 'objects'
        and cmd in ('INSERT', 'ALL')
        and (coalesce(qual, '') like '%supplier-evidence%' or coalesce(with_check, '') like '%supplier-evidence%')
    )
  and exists (
      select 1
      from pg_policies
      where schemaname = 'storage'
        and tablename = 'objects'
        and cmd in ('SELECT', 'ALL')
        and (coalesce(qual, '') like '%supplier-evidence%' or coalesce(with_check, '') like '%supplier-evidence%')
    ),
  'P0.9-AUTH-001 bucket:storage.supplier-evidence authorization mapping'
);

-- P0.9-AUTH: P0.9-AUTH-002
select ok(
  exists (
    select 1
    from pg_class c
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public'
      and c.relname = 'cbam_alerts'
      and c.relkind in ('r', 'p')
      and c.relrowsecurity
  )
  and exists (
      select 1
      from pg_policies
      where schemaname = 'public'
        and tablename = 'cbam_alerts'
        and cmd in ('SELECT', 'ALL')
        and coalesce(qual, '') !~* '^\s*false\s*$'
        and coalesce(with_check, '') !~* '^\s*false\s*$'
    ),
  'P0.9-AUTH-002 relation:public.cbam_alerts authorization mapping'
);

-- P0.9-AUTH: P0.9-AUTH-003
select ok(
  exists (
    select 1
    from pg_class c
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public'
      and c.relname = 'cbam_audit_log'
      and c.relkind in ('r', 'p')
      and c.relrowsecurity
  )
  and exists (
      select 1
      from pg_policies
      where schemaname = 'public'
        and tablename = 'cbam_audit_log'
        and cmd in ('SELECT', 'ALL')
        and coalesce(qual, '') !~* '^\s*false\s*$'
        and coalesce(with_check, '') !~* '^\s*false\s*$'
    ),
  'P0.9-AUTH-003 relation:public.cbam_audit_log authorization mapping'
);

-- P0.9-AUTH: P0.9-AUTH-004
select ok(
  exists (
    select 1
    from pg_class c
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public'
      and c.relname = 'cbam_certificate_carryover'
      and c.relkind = 'v'
      and coalesce(c.reloptions, array[]::text[]) @> array['security_invoker=true']::text[]
  ),
  'P0.9-AUTH-004 relation:public.cbam_certificate_carryover authorization mapping'
);

-- P0.9-AUTH: P0.9-AUTH-005
select ok(
  exists (
    select 1
    from pg_class c
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public'
      and c.relname = 'cbam_certificate_coverage'
      and c.relkind = 'v'
      and coalesce(c.reloptions, array[]::text[]) @> array['security_invoker=true']::text[]
  ),
  'P0.9-AUTH-005 relation:public.cbam_certificate_coverage authorization mapping'
);

-- P0.9-AUTH: P0.9-AUTH-006
select ok(
  exists (
    select 1
    from pg_class c
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public'
      and c.relname = 'cbam_certificate_forecast'
      and c.relkind = 'v'
      and coalesce(c.reloptions, array[]::text[]) @> array['security_invoker=true']::text[]
  ),
  'P0.9-AUTH-006 relation:public.cbam_certificate_forecast authorization mapping'
);

-- P0.9-AUTH: P0.9-AUTH-007
select ok(
  exists (
    select 1
    from pg_class c
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public'
      and c.relname = 'cbam_certificate_purchases'
      and c.relkind in ('r', 'p')
      and c.relrowsecurity
  )
  and exists (
      select 1
      from pg_policies
      where schemaname = 'public'
        and tablename = 'cbam_certificate_purchases'
        and cmd in ('INSERT', 'ALL')
        and coalesce(qual, '') !~* '^\s*false\s*$'
        and coalesce(with_check, '') !~* '^\s*false\s*$'
    )
  and exists (
      select 1
      from pg_policies
      where schemaname = 'public'
        and tablename = 'cbam_certificate_purchases'
        and cmd in ('SELECT', 'ALL')
        and coalesce(qual, '') !~* '^\s*false\s*$'
        and coalesce(with_check, '') !~* '^\s*false\s*$'
    ),
  'P0.9-AUTH-007 relation:public.cbam_certificate_purchases authorization mapping'
);

-- P0.9-AUTH: P0.9-AUTH-008
select ok(
  exists (
    select 1
    from pg_class c
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public'
      and c.relname = 'cbam_risk_scores'
      and c.relkind in ('r', 'p')
      and c.relrowsecurity
  )
  and exists (
      select 1
      from pg_policies
      where schemaname = 'public'
        and tablename = 'cbam_risk_scores'
        and cmd in ('SELECT', 'ALL')
        and coalesce(qual, '') !~* '^\s*false\s*$'
        and coalesce(with_check, '') !~* '^\s*false\s*$'
    ),
  'P0.9-AUTH-008 relation:public.cbam_risk_scores authorization mapping'
);

-- P0.9-AUTH: P0.9-AUTH-009
select ok(
  exists (
    select 1
    from pg_class c
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public'
      and c.relname = 'import_lines'
      and c.relkind in ('r', 'p')
      and c.relrowsecurity
  )
  and exists (
      select 1
      from pg_policies
      where schemaname = 'public'
        and tablename = 'import_lines'
        and cmd in ('SELECT', 'ALL')
        and coalesce(qual, '') !~* '^\s*false\s*$'
        and coalesce(with_check, '') !~* '^\s*false\s*$'
    ),
  'P0.9-AUTH-009 relation:public.import_lines authorization mapping'
);

-- P0.9-AUTH: P0.9-AUTH-010
select ok(
  exists (
    select 1
    from pg_class c
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public'
      and c.relname = 'imports'
      and c.relkind in ('r', 'p')
      and c.relrowsecurity
  )
  and exists (
      select 1
      from pg_policies
      where schemaname = 'public'
        and tablename = 'imports'
        and cmd in ('SELECT', 'ALL')
        and coalesce(qual, '') !~* '^\s*false\s*$'
        and coalesce(with_check, '') !~* '^\s*false\s*$'
    ),
  'P0.9-AUTH-010 relation:public.imports authorization mapping'
);

-- P0.9-AUTH: P0.9-AUTH-011
select ok(
  exists (
    select 1
    from pg_class c
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public'
      and c.relname = 'legal_entities'
      and c.relkind in ('r', 'p')
      and c.relrowsecurity
  )
  and exists (
      select 1
      from pg_policies
      where schemaname = 'public'
        and tablename = 'legal_entities'
        and cmd in ('INSERT', 'ALL')
        and coalesce(qual, '') !~* '^\s*false\s*$'
        and coalesce(with_check, '') !~* '^\s*false\s*$'
    )
  and exists (
      select 1
      from pg_policies
      where schemaname = 'public'
        and tablename = 'legal_entities'
        and cmd in ('SELECT', 'ALL')
        and coalesce(qual, '') !~* '^\s*false\s*$'
        and coalesce(with_check, '') !~* '^\s*false\s*$'
    )
  and exists (
      select 1
      from pg_policies
      where schemaname = 'public'
        and tablename = 'legal_entities'
        and cmd in ('UPDATE', 'ALL')
        and coalesce(qual, '') !~* '^\s*false\s*$'
        and coalesce(with_check, '') !~* '^\s*false\s*$'
    ),
  'P0.9-AUTH-011 relation:public.legal_entities authorization mapping'
);

-- P0.9-AUTH: P0.9-AUTH-012
select ok(
  exists (
    select 1
    from pg_class c
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public'
      and c.relname = 'memberships'
      and c.relkind in ('r', 'p')
      and c.relrowsecurity
  )
  and exists (
      select 1
      from pg_policies
      where schemaname = 'public'
        and tablename = 'memberships'
        and cmd in ('DELETE', 'ALL')
        and coalesce(qual, '') !~* '^\s*false\s*$'
        and coalesce(with_check, '') !~* '^\s*false\s*$'
    )
  and exists (
      select 1
      from pg_policies
      where schemaname = 'public'
        and tablename = 'memberships'
        and cmd in ('SELECT', 'ALL')
        and coalesce(qual, '') !~* '^\s*false\s*$'
        and coalesce(with_check, '') !~* '^\s*false\s*$'
    )
  and exists (
      select 1
      from pg_policies
      where schemaname = 'public'
        and tablename = 'memberships'
        and cmd in ('UPDATE', 'ALL')
        and coalesce(qual, '') !~* '^\s*false\s*$'
        and coalesce(with_check, '') !~* '^\s*false\s*$'
    ),
  'P0.9-AUTH-012 relation:public.memberships authorization mapping'
);

-- P0.9-AUTH: P0.9-AUTH-013
select ok(
  exists (
    select 1
    from pg_class c
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public'
      and c.relname = 'organizations'
      and c.relkind in ('r', 'p')
      and c.relrowsecurity
  )
  and exists (
      select 1
      from pg_policies
      where schemaname = 'public'
        and tablename = 'organizations'
        and cmd in ('SELECT', 'ALL')
        and coalesce(qual, '') !~* '^\s*false\s*$'
        and coalesce(with_check, '') !~* '^\s*false\s*$'
    ),
  'P0.9-AUTH-013 relation:public.organizations authorization mapping'
);

-- P0.9-AUTH: P0.9-AUTH-014
select ok(
  exists (
    select 1
    from pg_class c
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public'
      and c.relname = 'report_items'
      and c.relkind in ('r', 'p')
      and c.relrowsecurity
  )
  and exists (
      select 1
      from pg_policies
      where schemaname = 'public'
        and tablename = 'report_items'
        and cmd in ('SELECT', 'ALL')
        and coalesce(qual, '') !~* '^\s*false\s*$'
        and coalesce(with_check, '') !~* '^\s*false\s*$'
    ),
  'P0.9-AUTH-014 relation:public.report_items authorization mapping'
);

-- P0.9-AUTH: P0.9-AUTH-015
select ok(
  exists (
    select 1
    from pg_class c
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public'
      and c.relname = 'reports'
      and c.relkind in ('r', 'p')
      and c.relrowsecurity
  )
  and exists (
      select 1
      from pg_policies
      where schemaname = 'public'
        and tablename = 'reports'
        and cmd in ('SELECT', 'ALL')
        and coalesce(qual, '') !~* '^\s*false\s*$'
        and coalesce(with_check, '') !~* '^\s*false\s*$'
    ),
  'P0.9-AUTH-015 relation:public.reports authorization mapping'
);

-- P0.9-AUTH: P0.9-AUTH-016
select ok(
  exists (
    select 1
    from pg_class c
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public'
      and c.relname = 'scenario_exposure_by_dimension'
      and c.relkind = 'v'
      and coalesce(c.reloptions, array[]::text[]) @> array['security_invoker=true']::text[]
  ),
  'P0.9-AUTH-016 relation:public.scenario_exposure_by_dimension authorization mapping'
);

-- P0.9-AUTH: P0.9-AUTH-017
select ok(
  exists (
    select 1
    from pg_class c
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public'
      and c.relname = 'supplier_portal_submissions'
      and c.relkind in ('r', 'p')
      and c.relrowsecurity
  )
  and exists (
      select 1
      from pg_policies
      where schemaname = 'public'
        and tablename = 'supplier_portal_submissions'
        and cmd in ('SELECT', 'ALL')
        and coalesce(qual, '') !~* '^\s*false\s*$'
        and coalesce(with_check, '') !~* '^\s*false\s*$'
    ),
  'P0.9-AUTH-017 relation:public.supplier_portal_submissions authorization mapping'
);

-- P0.9-AUTH: P0.9-AUTH-018
select ok(
  exists (
    select 1
    from pg_class c
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public'
      and c.relname = 'supplier_request_campaigns'
      and c.relkind in ('r', 'p')
      and c.relrowsecurity
  )
  and exists (
      select 1
      from pg_policies
      where schemaname = 'public'
        and tablename = 'supplier_request_campaigns'
        and cmd in ('SELECT', 'ALL')
        and coalesce(qual, '') !~* '^\s*false\s*$'
        and coalesce(with_check, '') !~* '^\s*false\s*$'
    ),
  'P0.9-AUTH-018 relation:public.supplier_request_campaigns authorization mapping'
);

-- P0.9-AUTH: P0.9-AUTH-019
select ok(
  exists (
    select 1
    from pg_class c
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public'
      and c.relname = 'suppliers'
      and c.relkind in ('r', 'p')
      and c.relrowsecurity
  )
  and exists (
      select 1
      from pg_policies
      where schemaname = 'public'
        and tablename = 'suppliers'
        and cmd in ('SELECT', 'ALL')
        and coalesce(qual, '') !~* '^\s*false\s*$'
        and coalesce(with_check, '') !~* '^\s*false\s*$'
    ),
  'P0.9-AUTH-019 relation:public.suppliers authorization mapping'
);

-- P0.9-AUTH: P0.9-AUTH-020
select ok(
  exists (
    select 1
    from pg_proc p
    join pg_namespace n on n.oid = p.pronamespace
    where n.nspname = 'public'
      and p.proname = 'create_supplier_portal_token_for_request'
      and has_function_privilege('authenticated', p.oid, 'EXECUTE')
  ),
  'P0.9-AUTH-020 rpc:public.create_supplier_portal_token_for_request authorization mapping'
);

-- P0.9-AUTH: P0.9-AUTH-021
select ok(
  exists (
    select 1
    from pg_proc p
    join pg_namespace n on n.oid = p.pronamespace
    where n.nspname = 'public'
      and p.proname = 'create_supplier_request_campaign_from_requests'
      and has_function_privilege('authenticated', p.oid, 'EXECUTE')
  ),
  'P0.9-AUTH-021 rpc:public.create_supplier_request_campaign_from_requests authorization mapping'
);

-- P0.9-AUTH: P0.9-AUTH-022
select ok(
  exists (
    select 1
    from pg_proc p
    join pg_namespace n on n.oid = p.pronamespace
    where n.nspname = 'public'
      and p.proname = 'create_supplier_request_with_token'
      and has_function_privilege('authenticated', p.oid, 'EXECUTE')
  ),
  'P0.9-AUTH-022 rpc:public.create_supplier_request_with_token authorization mapping'
);

-- P0.9-AUTH: P0.9-AUTH-023
select ok(
  exists (
    select 1
    from pg_proc p
    join pg_namespace n on n.oid = p.pronamespace
    where n.nspname = 'public'
      and p.proname = 'get_legal_entity_address'
      and has_function_privilege('authenticated', p.oid, 'EXECUTE')
  ),
  'P0.9-AUTH-023 rpc:public.get_legal_entity_address authorization mapping'
);

-- P0.9-AUTH: P0.9-AUTH-024
select ok(
  exists (
    select 1
    from pg_proc p
    join pg_namespace n on n.oid = p.pronamespace
    where n.nspname = 'public'
      and p.proname = 'get_supplier_portal_context'
      and has_function_privilege('anon', p.oid, 'EXECUTE')
  ),
  'P0.9-AUTH-024 rpc:public.get_supplier_portal_context authorization mapping'
);

-- P0.9-AUTH: P0.9-AUTH-025
select ok(
  exists (
    select 1
    from pg_proc p
    join pg_namespace n on n.oid = p.pronamespace
    where n.nspname = 'public'
      and p.proname = 'issue_supplier_request_campaign_batch'
      and has_function_privilege('authenticated', p.oid, 'EXECUTE')
  ),
  'P0.9-AUTH-025 rpc:public.issue_supplier_request_campaign_batch authorization mapping'
);

-- P0.9-AUTH: P0.9-AUTH-026
select ok(
  exists (
    select 1
    from pg_proc p
    join pg_namespace n on n.oid = p.pronamespace
    where n.nspname = 'public'
      and p.proname = 'list_report_items_for_importer'
      and has_function_privilege('authenticated', p.oid, 'EXECUTE')
  ),
  'P0.9-AUTH-026 rpc:public.list_report_items_for_importer authorization mapping'
);

-- P0.9-AUTH: P0.9-AUTH-027
select ok(
  exists (
    select 1
    from pg_proc p
    join pg_namespace n on n.oid = p.pronamespace
    where n.nspname = 'public'
      and p.proname = 'list_supplier_requests_for_importer'
      and has_function_privilege('authenticated', p.oid, 'EXECUTE')
  ),
  'P0.9-AUTH-027 rpc:public.list_supplier_requests_for_importer authorization mapping'
);

-- P0.9-AUTH: P0.9-AUTH-028
select ok(
  exists (
    select 1
    from pg_proc p
    join pg_namespace n on n.oid = p.pronamespace
    where n.nspname = 'public'
      and p.proname = 'list_supplier_submissions_for_importer'
      and has_function_privilege('authenticated', p.oid, 'EXECUTE')
  ),
  'P0.9-AUTH-028 rpc:public.list_supplier_submissions_for_importer authorization mapping'
);

-- P0.9-AUTH: P0.9-AUTH-029
select ok(
  exists (
    select 1
    from pg_proc p
    join pg_namespace n on n.oid = p.pronamespace
    where n.nspname = 'public'
      and p.proname = 'list_suppliers_for_importer'
      and has_function_privilege('authenticated', p.oid, 'EXECUTE')
  ),
  'P0.9-AUTH-029 rpc:public.list_suppliers_for_importer authorization mapping'
);

-- P0.9-AUTH: P0.9-AUTH-030
select ok(
  exists (
    select 1
    from pg_proc p
    join pg_namespace n on n.oid = p.pronamespace
    where n.nspname = 'public'
      and p.proname = 'mark_supplier_request_viewed'
      and has_function_privilege('anon', p.oid, 'EXECUTE')
  ),
  'P0.9-AUTH-030 rpc:public.mark_supplier_request_viewed authorization mapping'
);

-- P0.9-AUTH: P0.9-AUTH-031
select ok(
  exists (
    select 1
    from pg_proc p
    join pg_namespace n on n.oid = p.pronamespace
    where n.nspname = 'public'
      and p.proname = 'set_default_legal_entity_for_org'
      and has_function_privilege('authenticated', p.oid, 'EXECUTE')
  ),
  'P0.9-AUTH-031 rpc:public.set_default_legal_entity_for_org authorization mapping'
);

-- P0.9-AUTH: P0.9-AUTH-032
select ok(
  exists (
    select 1
    from pg_proc p
    join pg_namespace n on n.oid = p.pronamespace
    where n.nspname = 'public'
      and p.proname = 'set_supplier_request_campaign_status'
      and has_function_privilege('authenticated', p.oid, 'EXECUTE')
  ),
  'P0.9-AUTH-032 rpc:public.set_supplier_request_campaign_status authorization mapping'
);

-- P0.9-AUTH: P0.9-AUTH-033
select ok(
  exists (
    select 1
    from pg_proc p
    join pg_namespace n on n.oid = p.pronamespace
    where n.nspname = 'public'
      and p.proname = 'submit_supplier_portal_submission'
      and has_function_privilege('anon', p.oid, 'EXECUTE')
  ),
  'P0.9-AUTH-033 rpc:public.submit_supplier_portal_submission authorization mapping'
);

-- P0.9-AUTH: P0.9-AUTH-034
select ok(
  exists (
    select 1
    from pg_proc p
    join pg_namespace n on n.oid = p.pronamespace
    where n.nspname = 'public'
      and p.proname = 'upsert_legal_entity_address'
      and has_function_privilege('authenticated', p.oid, 'EXECUTE')
  ),
  'P0.9-AUTH-034 rpc:public.upsert_legal_entity_address authorization mapping'
);

-- P0.9-AUTH: P0.9-AUTH-035
select ok(
  exists (
    select 1
    from pg_proc p
    join pg_namespace n on n.oid = p.pronamespace
    where n.nspname = 'public'
      and p.proname = 'validate_supplier_token'
      and has_function_privilege('anon', p.oid, 'EXECUTE')
  ),
  'P0.9-AUTH-035 rpc:public.validate_supplier_token authorization mapping'
);

select * from finish();
rollback;
